/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.dni.pvim.ext.telegram.repo.db.vo;

import id.dni.pvim.ext.repo.db.vo.FieldData;
import id.dni.pvim.ext.repo.db.vo.ITableDescriptorVo;
import id.dni.pvim.ext.repo.exceptions.PvExtPersistenceException;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *create table [pvim].[dbo].[PVIM_EXT_TELEGRAM_SUBSCRIBERS] (
	subs_id varchar(32) not null, 	-- random guid 32-digit string
	chat_id bigint not null, 		-- chat id from telegram Chat object
	phone_num varchar(32) not null, -- subscriber phone number
	lastupdate datetime not null,		-- last update as usual
	passkey varchar(32) not null,	-- autogenerated, to unsubscribe, probably just 6 digits or so...
	constraint pk_subs primary key (subs_id),
	constraint unq_recipient unique(phone_num, chat_id)
);
 * @author darryl.sulistyan
 */
public class TelegramSubscriberVo implements ITableDescriptorVo {
    
    public static final String TABLE_NAME = "PVIM_EXT_TELEGRAM_SUBSCRIBERS";
    public static final String FIELD_SUBS_ID = "SUBS_ID";
    public static final String FIELD_CHAT_ID = "CHAT_ID";
    public static final String FIELD_PHONE_NUM = "PHONE_NUM";
    public static final String FIELD_LASTUPDATE = "LASTUPDATE";
    public static final String FIELD_PASSKEY = "PASSKEY";
    
    private final Map<String, FieldData> tbl;
    public TelegramSubscriberVo() {
        tbl = new HashMap<>();
        tbl.put(FIELD_SUBS_ID, new FieldData.Builder().setFieldName(FIELD_SUBS_ID).setPartOfPk(true).build());
        tbl.put(FIELD_CHAT_ID, new FieldData.Builder().setFieldName(FIELD_CHAT_ID).build());
        tbl.put(FIELD_PHONE_NUM, new FieldData.Builder().setFieldName(FIELD_PHONE_NUM).build());
        tbl.put(FIELD_LASTUPDATE, new FieldData.Builder().setFieldName(FIELD_LASTUPDATE).build());
        tbl.put(FIELD_PASSKEY, new FieldData.Builder().setFieldName(FIELD_PASSKEY).build());
    }
    
    private static long getLong(Object whatever) {
        if (whatever == null) {
            return 0;
        }
        
        String s = whatever.toString();
        try {
            return Long.parseLong(s);
        } catch (NumberFormatException e) {
            return 0;
        }
    }
    
    private static long o2l(Object date) throws PvExtPersistenceException {
        if (date instanceof java.sql.Timestamp) {
            return ((Timestamp) date).getTime();
        } else if (date instanceof java.sql.Date) {
            return ((Date) date).getTime();
        } else {
            throw new PvExtPersistenceException("Unknown type for date: " + date.getClass().getName());
        }
    }
    
    @Override
    public void fillDataFromMap(Map<String, Object> fromDB) throws PvExtPersistenceException {
        
        Logger.getLogger(this.getClass().getName()).log(Level.FINEST, "Read from DB: {0}", fromDB);
        for (Map.Entry<String, Object> k : fromDB.entrySet()) {
            tbl.get(k.getKey()).setValue(k.getValue());
        }
        
        this.setSubs_id((String) fromDB.get(FIELD_SUBS_ID));
        this.setLastupdate(o2l(fromDB.get(FIELD_LASTUPDATE)));
        this.setPasskey((String) fromDB.get(FIELD_PASSKEY));
        this.setPhone_num((String) fromDB.get(FIELD_PHONE_NUM));
        this.setChat_id(getLong(fromDB.get(FIELD_CHAT_ID)));
    }
    
    @Override
    public String getTableName() {
        return TABLE_NAME;
    }

    @Override
    public Map<String, FieldData> getFieldDescriptor() {
        return tbl;
    }
    
    private String subs_id;
    private long chat_id;
    private String phone_num;
    private long lastupdate;
    private String passkey;

    public String getSubs_id() {
        return subs_id;
    }

    public void setSubs_id(String subs_id) {
        this.subs_id = subs_id;
        tbl.get(FIELD_SUBS_ID).setValue(subs_id);
    }

    public long getChat_id() {
        return chat_id;
    }

    public void setChat_id(long chat_id) {
        this.chat_id = chat_id;
        tbl.get(FIELD_CHAT_ID).setValue(chat_id);
    }

    public String getPhone_num() {
        return phone_num;
    }

    public void setPhone_num(String phone_num) {
        this.phone_num = phone_num;
        tbl.get(FIELD_PHONE_NUM).setValue(phone_num);
    }

    public long getLastupdate() {
        return lastupdate;
    }

    public void setLastupdate(long lastupdate) {
        this.lastupdate = lastupdate;
        tbl.get(FIELD_LASTUPDATE).setValue(new Timestamp(lastupdate));
    }

    public String getPasskey() {
        return passkey;
    }

    public void setPasskey(String passkey) {
        this.passkey = passkey;
        tbl.get(FIELD_PASSKEY).setValue(passkey);
    }

    

    
    
    
    
    
}
